---
- name: End-to-End AIOps Self-Healing Platform
  hosts: all
  become: yes
  vars:
    # Infrastructure Versions
    loki_chart_version: "2.9.11"
    prometheus_chart_version: "45.7.1"
    loki_image_tag: "2.9.3"
    
    # Project Structure
    project_dir: "/home/ubuntu/aiops-project"
    venv_path: "{{ project_dir }}/venv"
    csv_filename: "ec2_cpu_utilization_5f5533.csv"

  tasks:
    # --- 1. System & Kubernetes Setup ---
    - name: Install system dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, python3-pip, python3-venv, net-tools]
        update_cache: yes

    - name: Create project directories
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
      loop:
        - "{{ project_dir }}/data"
        - "{{ project_dir }}/models"

    - name: Setup K3s and non-root kubectl
      shell: |
        curl -sfL https://get.k3s.io | sh -
        mkdir -p /home/ubuntu/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config
        chmod 600 /home/ubuntu/.kube/config
      args:
        creates: /home/ubuntu/.kube/config

    # --- 2. Observability & Connectivity FIX ---
    - name: Install Helm and Monitoring Stack
      become: no
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --version {{ prometheus_chart_version }}
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Patch Prometheus to NodePort and Get Port
      become: no
      shell: |
        kubectl patch svc prometheus-kube-prometheus-prometheus -n monitoring -p '{"spec":{"type":"NodePort"}}'
        kubectl get svc prometheus-kube-prometheus-prometheus -n monitoring -o jsonpath='{.spec.ports[0].nodePort}'
      register: prometheus_nodeport
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    # --- 3. Asset Deployment & ML Setup ---
    - name: Copy AIOps Python Scripts
      copy:
        src: "./{{ item }}"
        dest: "{{ project_dir }}/{{ item }}"
        owner: ubuntu
        group: ubuntu
      loop:
        - "main.py"
        - "train_isolation_forest.py"
        - "healer.py"
        - "{{ csv_filename }}"

    - name: Automate Fix for main.py (Inject NodePort and Absolute Path)
      replace:
        path: "{{ project_dir }}/main.py"
        regexp: 'PROMETHEUS_URL = ".*"'
        replace: 'PROMETHEUS_URL = "http://localhost:{{ prometheus_nodeport.stdout }}"'

    - name: Update MODEL_PATH to Absolute
      replace:
        path: "{{ project_dir }}/main.py"
        regexp: 'MODEL_PATH = "models/iso_forest.joblib"'
        replace: 'MODEL_PATH = "{{ project_dir }}/models/iso_forest.joblib"'

    - name: Install ML Libraries and Train Model
      pip:
        name: [pandas, scikit-learn, joblib, fastapi, uvicorn, matplotlib, prometheus-api-client]
        virtualenv: "{{ venv_path }}"
        virtualenv_command: "/usr/bin/python3 -m venv"

    - name: Execute Model Training
      become: no
      shell: "{{ venv_path }}/bin/python {{ project_dir }}/train_isolation_forest.py"
      args:
        chdir: "{{ project_dir }}"

    # --- 4. Deployment of Services (API & Healer) ---
    - name: Deploy Systemd Services
      copy:
        dest: "/etc/systemd/system/{{ item.name }}.service"
        content: |
          [Unit]
          Description={{ item.desc }}
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ project_dir }}
          Environment="PATH={{ venv_path }}/bin"
          Environment="KUBECONFIG=/home/ubuntu/.kube/config"
          ExecStart={{ item.cmd }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
      loop:
        - { name: 'fastapi', desc: 'AIOps API', cmd: "{{ venv_path }}/bin/uvicorn main:app --host 0.0.0.0 --port 8000" }
        - { name: 'healer', desc: 'AIOps Healer', cmd: "{{ venv_path }}/bin/python {{ project_dir }}/healer.py" }

    - name: Start AIOps Services
      systemd_service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      loop: [fastapi, healer]

    # --- 5. Chaos Loop Setup ---
    - name: Create Chaos Deployment Manifest
      copy:
        dest: "{{ project_dir }}/chaos-deployment.yaml"
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: chaos-spike-generator
            namespace: monitoring
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: chaos-worker
            template:
              metadata:
                labels:
                  app: chaos-worker
              spec:
                containers:
                - name: stress
                  image: polinux/stress-ng:latest
                  args: ["--cpu", "2", "--timeout", "600s"]
      
    - name: Apply Chaos Deployment
      become: no
      shell: kubectl apply -f {{ project_dir }}/chaos-deployment.yaml
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"
