---
- name: Configure AIOps Platform on EC2
  hosts: all
  become: yes  # System-wide default for K3s/Helm installation
  vars:
    # Pinning versions to prevent future compatibility issues
    loki_chart_version: "2.9.11"
    prometheus_chart_version: "45.7.1"
    loki_image_tag: "2.9.3"  # Fixed compatibility with newer Grafana versions

  tasks:
    - name: Update apt and install dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, python3-pip]
        update_cache: yes

    - name: Install K3s (Lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      pause:
        seconds: 20

    - name: Create .kube directory
      file:
        path: "/home/ubuntu/.kube"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy K3s config to ubuntu user's home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Helm Repositories
      become: no # Ensure repos are added to ubuntu user context
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Install Prometheus Stack
      become: no
      shell: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
        --namespace monitoring --create-namespace \
        --version {{ prometheus_chart_version }} \
        --set grafana.sidecar.datasources.enabled=true \
        --set grafana.sidecar.datasources.label=grafana_datasource \
        --set grafana.sidecar.datasources.defaultDatasourceEnabled=true
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Install Loki with Memberlist and Version Fix
      become: no
      shell: |
        helm upgrade --install loki grafana/loki-stack \
        --namespace monitoring \
        --version {{ loki_chart_version }} \
        --set loki.image.tag={{ loki_image_tag }} \
        --set loki.
