---
- name: End-to-End AIOps Self-Healing Platform
  hosts: all
  become: yes
  vars:
    # Infrastructure Versions
    loki_chart_version: "2.9.11"
    prometheus_chart_version: "45.7.1"
    loki_image_tag: "2.9.3"
    
    # Project Structure
    project_dir: "/home/ubuntu/aiops-project"
    venv_path: "{{ project_dir }}/venv"
    csv_filename: "ec2_cpu_utilization_5f5533.csv"

  tasks:
    # --- 1. System & Kubernetes Setup ---
    
    - name: Install system dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, python3-pip, python3-venv, net-tools]
        update_cache: yes

    - name: Create project directories
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - "{{ project_dir }}"
        - "{{ project_dir }}/data"
        - "{{ project_dir }}/models"

    - name: Setup K3s and non-root kubectl
      shell: |
        curl -sfL https://get.k3s.io | sh -
        mkdir -p /home/ubuntu/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config
        chmod 600 /home/ubuntu/.kube/config
      args:
        creates: /home/ubuntu/.kube/config

    # --- 2. Observability & Connectivity FIX ---
    
    - name: Install Helm and Monitoring Stack
      become: no
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --version {{ prometheus_chart_version }}
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Patch Prometheus to NodePort and Get Port (Sanitized)
      become: no
      shell: |
        kubectl patch svc prometheus-kube-prometheus-prometheus -n monitoring -p '{"spec":{"type":"NodePort"}}' > /dev/null
        kubectl get svc prometheus-kube-prometheus-prometheus -n monitoring -o jsonpath='{.spec.ports[0].nodePort}'
      register: prometheus_nodeport
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    # --- 3. Asset Deployment & ML Setup ---
    
    - name: Copy AIOps Python Scripts and Data
      copy:
        src: "./{{ item.src }}"
        dest: "{{ project_dir }}/{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
      loop:
        - { src: "main.py", dest: "main.py" }
        - { src: "train_isolation_forest.py", dest: "train_isolation_forest.py" }
        - { src: "healer.py", dest: "healer.py" }
        - { src: "{{ csv_filename }}", dest: "data/{{ csv_filename }}" }

    - name: Automate Fix for main.py (Inject NodePort Safely)
      replace:
        path: "{{ project_dir }}/main.py"
        regexp: '^PROMETHEUS_URL = .*'
        replace: 'PROMETHEUS_URL = "http://localhost:{{ prometheus_nodeport.stdout | trim }}"'

    - name: Update MODEL_PATH to Absolute in main.py
      replace:
        path: "{{ project_dir }}/main.py"
        regexp: '^MODEL_PATH = .*'
        replace: 'MODEL_PATH = "{{ project_dir }}/models/iso_forest.joblib"'

    - name: Install ML Libraries
      pip:
        name: [pandas, scikit-
